namespace Dmg.Core.Tests.Containers;

/// <summary>
/// Bytes lifted verbatim out of an image produced by <c>hdiutil</c> on macOS 15.
/// </summary>
/// <remarks>
/// <para>
/// The image was made with
/// <c>hdiutil create -srcfolder … -fs "MS-DOS FAT32" -format UDZO -volname TESTVOL</c>
/// and is 74,814 bytes: a protective MBR region of one sector plus a 67,646-sector
/// FAT32 region, 67,647 sectors of decoded disk in total.
/// </para>
/// <para>
/// These constants exist so the parsers are checked against a real Apple-written
/// container and not only against structures this test suite invented. The field
/// offsets in <c>docs/03-udif-format-reference.md</c> are marked unverified; where
/// the document and these bytes disagree, these bytes win.
/// </para>
/// </remarks>
internal static class RealImageSamples
{
    /// <summary>The total size of the image the samples were taken from.</summary>
    public const long FileLength = 74814;

    /// <summary>The 512-byte koly trailer, base64-encoded.</summary>
    public const string KolyBase64 =
        "a29seQAAAAQAAAIAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEULgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAABFC4AAAAAAAAOEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAg" +
        "veeInAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAABCD8AAAAA" +
        "AAAAAAAAAAA=";

    /// <summary>The koly trailer as bytes.</summary>
    public static byte[] Koly() => Convert.FromBase64String(KolyBase64);

    /// <summary>
    /// The XML property list from that image, base64-encoded so it survives in a
    /// source file byte for byte - doctype declaration, tabs, wrapped base64 inside
    /// the &lt;data&gt; elements and all.
    /// </summary>
    public const string PlistBase64 =
        "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUv" +
        "L0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+Cjxw" +
        "bGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+cmVzb3VyY2UtZm9yazwva2V5PgoJPGRpY3Q+CgkJPGtleT5ibGt4" +
        "PC9rZXk+CgkJPGFycmF5PgoJCQk8ZGljdD4KCQkJCTxrZXk+QXR0cmlidXRlczwva2V5PgoJCQkJPHN0cmluZz4weDAwNTA8" +
        "L3N0cmluZz4KCQkJCTxrZXk+Q0ZOYW1lPC9rZXk+CgkJCQk8c3RyaW5nPk1hc3RlciBCb290IFJlY29yZCAoTUJSIDogMCk8" +
        "L3N0cmluZz4KCQkJCTxrZXk+RGF0YTwva2V5PgoJCQkJPGRhdGE+CgkJCQliV2x6YUFBQUFBRUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQkFBQUFBQUFBQUFBQQoJCQkJQUFnSUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCQkJCUFB" +
        "SUFBQUFnU2cySGRnQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCgkJCQlBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCQkJ" +
        "CUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCgkJCQlBQUFBQUFBQ2dBQUFCUUFBQUhVQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFCQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUgvLy8vLzhBQUFBQUFBQUFBQUFBQUFFQUFBQUEK" +
        "CQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQT0KCQkJCTwvZGF0YT4KCQkJCTxrZXk+SUQ8L2tleT4KCQkJCTxzdHJp" +
        "bmc+LTE8L3N0cmluZz4KCQkJCTxrZXk+TmFtZTwva2V5PgoJCQkJPHN0cmluZz5NYXN0ZXIgQm9vdCBSZWNvcmQgKE1CUiA6" +
        "IDApPC9zdHJpbmc+CgkJCTwvZGljdD4KCQkJPGRpY3Q+CgkJCQk8a2V5PkF0dHJpYnV0ZXM8L2tleT4KCQkJCTxzdHJpbmc+" +
        "MHgwMDUwPC9zdHJpbmc+CgkJCQk8a2V5PkNGTmFtZTwva2V5PgoJCQkJPHN0cmluZz4gKERPU19GQVRfMzIgOiAxKTwvc3Ry" +
        "aW5nPgoJCQkJPGtleT5EYXRhPC9rZXk+CgkJCQk8ZGF0YT4KCQkJCWJXbHphQUFBQUFFQUFBQUFBQUFBQVFBQUFBQUFBUWcr" +
        "QUFBQUFBQUFBQUFBCgkJCQlBQWdJQUFBQUFRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFJQUFB" +
        "QWdKcEtsTGdBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBCgkJCQlBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCQkJCUFBQUFBQUFFZ0FBQUJRQUFBSFVBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBVFVBQUFBCgkJCQlBQUFBQUI4QUFBQUFBQUVVRHdBQUFBSUFBQUIxQUFBQUFBQUFCTlFBQUFBQQoJCQkJ" +
        "QUFBREt3QUFBQUFBQVJRdUFBQUFBQUFBQUFBQUFBQUNBQUFBQUFBQUFBQUEKCQkJCUFBZi9BQUFBQUFBQkFEOEFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQS8vLy8vd0FBCgkJCQlBQUFBQUFBQUFBRUlQZ0FBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJ" +
        "CQkJQUE9PQoJCQkJPC9kYXRhPgoJCQkJPGtleT5JRDwva2V5PgoJCQkJPHN0cmluZz4wPC9zdHJpbmc+CgkJCQk8a2V5Pk5h" +
        "bWU8L2tleT4KCQkJCTxzdHJpbmc+IChET1NfRkFUXzMyIDogMSk8L3N0cmluZz4KCQkJPC9kaWN0PgoJCTwvYXJyYXk+CgkJ" +
        "PGtleT5wbHN0PC9rZXk+CgkJPGFycmF5PgoJCQk8ZGljdD4KCQkJCTxrZXk+QXR0cmlidXRlczwva2V5PgoJCQkJPHN0cmlu" +
        "Zz4weDAwNTA8L3N0cmluZz4KCQkJCTxrZXk+RGF0YTwva2V5PgoJCQkJPGRhdGE+CgkJCQlBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCgkJCQlBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCgkJCQlBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCgkJCQlBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCgkJCQlBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCgkJCQlBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFFQUFRQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCgkJCQlB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCgkJ" +
        "CQlBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "CgkJCQlBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBCgkJCQlBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKCQkJCUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB" +
        "QUFBQUFBCgkJCQlBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQoJCQkJQUFBQUFBQUFBQUFB" +
        "CgkJCQk8L2RhdGE+CgkJCQk8a2V5PklEPC9rZXk+CgkJCQk8c3RyaW5nPjA8L3N0cmluZz4KCQkJCTxrZXk+TmFtZTwva2V5" +
        "PgoJCQkJPHN0cmluZz48L3N0cmluZz4KCQkJPC9kaWN0PgoJCTwvYXJyYXk+Cgk8L2RpY3Q+CjwvZGljdD4KPC9wbGlzdD4K";

    /// <summary>The property list as UTF-8 bytes, exactly as hdiutil wrote them.</summary>
    public static byte[] PlistUtf8() => Convert.FromBase64String(PlistBase64);

    /// <summary>The property list as text.</summary>
    public static string PlistText() => System.Text.Encoding.UTF8.GetString(PlistUtf8());
}
